# Page settings

baseURL = ""
relativeURLs = "True"
languageCode = "en"
title = ""
theme = "hugo-devresume-theme"

publishDir = "docs"





[params]
    author = "CowboySmall"
    description = "DevResume - Bootstrap 4 Resume/CV Template For Software Developers"


    primaryColor = "#54B689"
    textPrimaryColor = "#292929"




    [params.profile]
        enable = true
        name = "邓东升（PhD）"
        tagline = ""
        avatar = "avatar.png"







    [params.contact]
        enable = true
        location = "上海-浦东"

        [[params.contact.list]]
        icon = "fas fa-phone-square"
        url = "tel:#"
        text = "186 1685 1373"
        [[params.contact.list]]
        icon = "fas fa-envelope-square"
        url = "mailto:#"
        text = "ddswhu@outlook.com"
        [[params.contact.list]]
        icon = "fas fa-globe"
        url = "#"
        text = "ds-deng.me"







    [params.skills]
        enable = true

        [[params.skills.list]]
        title = "编程技能"
        [[params.skills.list.items]]
        details = "Python/R 语言"
        [[params.skills.list.items]]
        details = "pandas/scipy/statsmodel/sklearn"
        [[params.skills.list.items]]
        details = "LR/RF/LGBM/LSTM"
        [[params.skills.list.items]]
        details = "MongoDB/MySQL/PostgreSQL"
        [[params.skills.list.items]]
        details = "LaTeX/Rmarkdown/Sphinx/Docstring"
        [[params.skills.list.items]]
        details = "Git/Github/Gitee"

        [[params.skills.list]]
        title = "经济学"
        [[params.skills.list.items]]
        details = "理论计量/实证计量"
        [[params.skills.list.items]]
        details = "因果推断（IV/PSM/SCM）"
        [[params.skills.list.items]]
        details = "时间序列/面板数据建模"









    [params.education]
        enable = true

        [[params.education.list]]
        degree = "数理金融试验班（本科）"
        university = "武汉大学"
        dates = "2009 - 2013"
        [[params.education.list]]
        degree = "世界经济学（硕士）"
        university = "复旦大学"
        dates = "2013 - 2016"
        [[params.education.list]]
        degree = "西方经济学（博士）"
        university = "复旦大学"
        dates = "2016 - 2019"








    [params.awards]
        enable = true

        [[params.awards.list]]
        name = "博士优秀毕业生"
        body = "复旦大学"
        date = "2019"
        [[params.awards.list]]
        name = "本科优秀毕业生"
        body = "武汉大学"
        date = "2013"
        [[params.awards.list]]
        name = "三好学生"
        body = "武汉大学"
        date = "2012"
        [[params.awards.list]]
        name = "博士生学术论坛（经济学）论文一等奖"
        body = "复旦大学"
        date = "2017"
        [[params.awards.list]]
        name = "美赛二等奖"
        body = ""
        date = "2012"






    [params.languages]
        enable = false

        [[params.languages.list]]
        name = "普通话"
        level = "母语"
        [[params.languages.list]]
        name = "英语"
        level = "熟练"
        [[params.languages.list]]
        name = "日语"
        level = "初级"








    [params.interests]
        enable = false

        [[params.interests.list]]
        name = "Climbing"
        [[params.interests.list]]
        name = "Snowboarding"
        [[params.interests.list]]
        name = "Photography"
        [[params.interests.list]]
        name = "Travelling"








    [params.summary]
        enable = true
        text = "我现在任职于平安科技投研与咨询团队。我在 2019 年从复旦大学博士毕业后来到平安科技的，部门服务对象主要为平安集团上层、政府单位（比如深圳市政府、统计局）以及外部的一些合作单位（比如金茂集团等）。我在 2019 年底转到房地产组之后主要做的是商业地产、商业住宅相关的研究。因为房地产是一个科技渗透率非常低的行业，早期我们对于行业的研究都是遵循业界的范式，围绕变量之间相关性、周期定位、周期拐点展开，预测使用的多为 ARIMA、VAR 等传统时序计量方法。后来我们逐渐把一些机器学习的方法应用到我们的项目中，主要项目有基于随机森林模型的房地产政策预测以及长租公寓租金定价模型、基于类重复交易模型的写字楼资产价格指数等。在此期间，我实现了从纯计量方法到机器学习的转变，也让我对未来的方向（数据科学家）更加明确。"








    [params.experience]
        enable = true

        [[params.experience.list]]
        title = "资深投资经理（数据分析）"
        dates = "2019.7- 至今"
        company = "平安科技"
        details = "主要从事房地产相关的研究工作。"
        [[params.experience.list.items]]
        details = "研究服务：研究方法调研、数据和算法探索，将机器学习算法、大数据应用到所负责的研究报告中；"
        [[params.experience.list.items]]
        details = "商业化：构建数据库，并对数据的应用场景进行探索，最终实现数据、模型的产品化，将其推广。"
        [[params.experience.list.items]]
        details = "考核结果： 年中、年终均为 A+ 绩效，排名前 5%。"






    [params.projects]
        enable = true

        [[params.projects.list]]
        title = "城市写字楼租金预测——基于领先性质的主成分因子模型"
        meta = "2019.10-2020.1"
        tagline = "从宏观、中观因子中筛选能够对于 4 个主要城市写字楼租金具有预测性的因子并做分类，检验每一类别下因子对于城市写字楼租金的领先性质与领先期数，根据因子的领先性进行特征工程，使用 PCA 对于每一类因子构建主成分因子 区分正负相关性 ，根据主成分因子和相关性，利用 sk-learn 对租金进行回归建模。成果：交付给平安不动产租金预测的文档、代码和城市 板块未来 1 年和 5 年的预测结果。"

        [[params.projects.list]]
        title = "房地产政策预测——基于非平衡样本的随机森林模型"
        meta = "2020.11-2021.4"
        tagline = "我们构建了房地产政策 4 级标签体系，将从 2015 年以来的各地房地产政策进行标签化，将非结构化数据转为结构化数据，在此基础上构建了房地产调控指数；其次与平安欧拉图谱团队 ，对历史房地产政策进行情感标注，结合标签体系，对各个城市房地产的数据（如新房、二手房、房价租金比、去化率等）做特征工程，使用 Logit Regression、Random Forest 和 XGBoost 等模型对各个城市房地产政策进行分类预测，在考虑正负样本的非平衡性后，最终 Balanced Accuracy 为 86% 左右。"

        [[params.projects.list]]
        title = "写字楼投资基准——基于 PSM 的价格指数"
        meta = "2021.5-2021.12"
        tagline = "写字楼的投资周期非常长，成本法难以计量写字楼投资的收益，因此平安需要写字楼投资基准作为投资参考。相同物业在多次交易时能够反映跨时的价格增长/指数；但写字楼交易数据比较少，因此我们尝试构建了 Pseudo Repeat Sales Model，在一个更大的匹配空间假定物业的同质性与可比性，并结合 Hedonic Model 去除写字楼自身特征的影响，构建写字楼投资基准/价格指数。"










    [params.information]
        enable = true

        [[params.information.list]]
        title = "论文"
        [[params.information.list.items]]
        details = "2011 年，国家大学生创新性实验计划, 《个税改革对城镇居民消费影响实证分析》。"
        [[params.information.list.items]]
        details = "2013 年，复旦大学暑期夏令营论文, 《政治不稳定下的通货膨胀选择》。"      
        [[params.information.list.items]]
        details = "2013 年，武汉大学本科毕业论文, 《在沪农民工汇款寄回与生活满意度—基于 OPM 模型》。"
        [[params.information.list.items]]
        details = "2019 年，复旦大学博士毕业论文，《互联网金融的发展、运营风险与监管政策评价》。"
        [[params.information.list.items]]
        details = "邓东升、陈钊：《互联网金融风险与投资者风险意识—来自网贷平台交易数据的证据》，《财贸经济》2019(02)。"
        [[params.information.list.items]]
        details = "陈钊、邓东升：《互联网金融发展、风险与监管-以 P2P 网络借贷为例》，《学术月刊》，2019(12)。"

        [[params.information.list]]
        title = "兴趣爱好"
        details = "球类运动（羽毛球、乒乓球）、旅游、看电影"








    [params.social]
        enable = true

        [[params.social.list]]
        icon = "fab fa-github-square"
        url = "//github.com/EthanDeng"
        title = "EthanDeng"
        [[params.social.list]]
        icon = "fab fa-linkedin"
        url = "//linkedin.com/in/dongshengdeng/"
        title = "dongshengdeng"
        [[params.social.list]]
        icon = "fab fa-twitter-square"
        url = "//twitter.com/ddswhu"
        title = "@ddswhu"





